### ISSUE TITLE
add requirements.txt

### ISSUE THREAD

**Issue by levzlotnik** [levavft/WukongGo#6]
To allow multiple users who are unfamiliar with your code base to get into business more easily - add a `requirements.txt` file. This file includes all the python dependencies of your project, and installing them is as easy as `pip install -r requirements.txt`.

**Comment by levzlotnik** [comment]
for more info - refer to [pip docs](https://pip.pypa.io/en/stable/user_guide/#requirements-files)

**Comment by YotamAlon** [comment]
Done in 57faec68399b1be5d230b28f890eff4936f2535c
